name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files '*.c' '*.h' | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make

      - name: Generate the standard password
        run: bin/pawg

      - name: Generate the password with capital letters
        run: bin/pawg -c

      - name: Generate multiple passwords
        run: bin/pawg 5

      - name: Generate multiple passwords in columnm, sized 13
        run: bin/pawg 4 13 -1

      - name: Generate multiple passwords with capital letters in column, sized 6
        run: bin/pawg 5 6 -1 -c

      - name: Generate password with numbers
        run: bin/pawg -n
      
      - name: Generate multiple passwords with numbers and capital letters
        run: bin/ pawg 5 -n -c